In [3]:
import numpy as np
import pandas as pd
import torch


In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [5]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN


In [6]:
df.drop(['id', 'Unnamed: 32'], inplace = True, axis = 1)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

xtrain, xtest, ytrain, ytest = train_test_split(df.drop(['diagnosis'], axis = 1), df['diagnosis'], test_size=0.2)

In [9]:
ytrain

,diagnosis
510,B
299,B
441,M
538,B
462,B
...,...
517,M
230,M
155,B
567,M


In [10]:
scalar = StandardScaler()
xtrain = scalar.fit_transform(xtrain)
xtest = scalar.transform(xtest)

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
ytrain = encoder.fit_transform(ytrain)
ytest = encoder.transform(ytest)

In [12]:
ytrain

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,

In [13]:
xtrain_tensor = torch.from_numpy(xtrain)
xtest_tensor = torch.from_numpy(xtest)
ytrain_tensor = torch.from_numpy(ytrain)
ytest_tensor = torch.from_numpy(ytest)

In [14]:
xtrain_tensor

tensor([[-0.6608, -1.0641, -0.6290,  ..., -0.1361, -0.4889,  0.8093],
        [-1.0096,  0.8714, -1.0186,  ..., -1.2639, -1.0948, -0.8837],
        [ 0.9073,  1.4083,  0.8573,  ...,  0.8999, -0.6561, -0.2468],
        ...,
        [-0.5162, -0.3153, -0.5483,  ..., -0.4925,  0.3291, -0.1442],
        [ 1.8516,  2.3093,  1.9980,  ...,  2.2818,  1.8945,  2.1853],
        [-1.4696, -1.0757, -1.3505,  ..., -1.0120, -1.0514,  1.3338]],
       dtype=torch.float64)

In [30]:
learning_rate = 0.1
epochs = 1000

In [16]:
xtrain_tensor.shape

torch.Size([455, 30])

In [22]:
class SimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True) ## creates a 30x1 matrix
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    return torch.sigmoid(z)

  def binary_cross_entropy(self, y_pred, y):
    EPSILON  = 1e-10
    y_pred = torch.clamp(y_pred, EPSILON, 1-EPSILON)

    loss = -torch.mean(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
    return loss


In [31]:
# creating model
model = SimpleNN(xtrain_tensor)
model.weights

tensor([[0.7972],
        [0.2018],
        [0.1265],
        [0.2013],
        [0.0665],
        [0.9680],
        [0.7598],
        [0.6261],
        [0.9518],
        [0.3840],
        [0.8736],
        [0.2892],
        [0.0235],
        [0.6693],
        [0.7934],
        [0.6418],
        [0.4282],
        [0.1107],
        [0.7470],
        [0.6302],
        [0.9368],
        [0.5107],
        [0.9701],
        [0.3871],
        [0.0752],
        [0.5659],
        [0.4900],
        [0.9908],
        [0.0428],
        [0.9053]], dtype=torch.float64, requires_grad=True)

In [24]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [32]:
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(xtrain_tensor)

  # loss calculate
  loss = model.binary_cross_entropy(y_pred, ytrain_tensor)
  print(f'epoch: {epoch+1}, loss: {loss.item()}')
  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

epoch: 1, loss: 4.233863182382093
epoch: 2, loss: 4.0650145015185215
epoch: 3, loss: 3.88951941038307
epoch: 4, loss: 3.714457779152084
epoch: 5, loss: 3.537973605722409
epoch: 6, loss: 3.357632569696988
epoch: 7, loss: 3.170977389318277
epoch: 8, loss: 2.982908765519824
epoch: 9, loss: 2.7955107355354327
epoch: 10, loss: 2.6062287645373816
epoch: 11, loss: 2.41731684044043
epoch: 12, loss: 2.228632694609302
epoch: 13, loss: 2.0442537671206873
epoch: 14, loss: 1.8630558544556863
epoch: 15, loss: 1.6906581015275193
epoch: 16, loss: 1.5291257869932384
epoch: 17, loss: 1.3807569675654616
epoch: 18, loss: 1.247885339386447
epoch: 19, loss: 1.1325413828520658
epoch: 20, loss: 1.036005709929185
epoch: 21, loss: 0.9583832465844141
epoch: 22, loss: 0.8983962148641059
epoch: 23, loss: 0.8535679795919209
epoch: 24, loss: 0.8207753114797015
epoch: 25, loss: 0.7969047939407291
epoch: 26, loss: 0.7793223193291056
epoch: 27, loss: 0.7660496644111924
epoch: 28, loss: 0.7557167378762198
epoch: 29, los

In [33]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(xtest_tensor)
  y_pred = (y_pred > 0.5).float()

In [34]:
accuracy = (y_pred == ytest_tensor).float().mean()
print(accuracy)

tensor(0.5877)
