In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

### Tensors

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tensor = torch.Tensor(arr)

In [ ]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
arr * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
tensor * 5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

In [ ]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
np.random.randint((2,4))

array([0, 1])

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
tensor = tensor.to('cuda')

In [ ]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')